import {  Outfit } from "next/font/google";
import "./globals.css";
const Outfitfont = Outfit({
   subsets: ["latin"],
});


export const metadata = {
    title: "Quarbani Hut",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${Outfitfont.className} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col w-10/12 mx-auto">
                
                {children}
                
            </body>
        </html>
    );
}
